def EngToDutchStopWords():
    eng_sw = ['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', 'too', 'very', 's', 't', 'can', 'will', 'just', 'don', "don't", 'should', "should've", 'now', 'd', 'll', 'm', 'o', 're', 've', 'y', 'ain', 'aren', "aren't", 'couldn', "couldn't", 'didn', "didn't", 'doesn', "doesn't", 'hadn', "hadn't", 'hasn', "hasn't", 'haven', "haven't", 'isn', "isn't", 'ma', 'mightn', "mightn't", 'mustn', "mustn't", 'needn', "needn't", 'shan', "shan't", 'shouldn', "shouldn't", 'wasn', "wasn't", 'weren', "weren't", 'won', "won't", 'wouldn', "wouldn't"]
    dut_sw=['ik', 'me', 'mijn', 'mezelf', 'wij', 'onze', 'Onze', 'onszelf', 'u', 'uw', 'uw', 'jezelf', 'uzelf', 'hij', 'hem', 'zijn', 'zichzelf', 'ze', 'haar', 'zijn', 'zichzelf', 'het', 'haar', 'zelf', 'ze', 'hen', 'hun', 'hun', 'zich', 'wat', 'welke', 'wie', 'wie', 'deze', 'dat', 'deze', 'die', 'am', 'is', 'zijn', 'was', 'waren', 'worden', 'geweest', 'wezen', 'hebben', 'heeft', 'had', 'met', 'Doen', 'doet', 'deed', 'doen', 'een', 'een', 'de', 'en', 'maar', 'als', 'of', 'omdat', 'als', 'tot', 'terwijl', 'van', 'Bij', 'door', 'voor', 'met', 'over', 'tegen', 'tussen', 'in', 'door', 'gedurende', 'voordat', 'na', 'bovenstaande', 'beneden', 'naar', 'van', 'omhoog', 'beneden', 'in', 'uit', 'Aan', 'uit', 'over-', 'onder', 'opnieuw', 'verder', 'vervolgens', 'eenmaal', 'hier', 'Daar', 'wanneer', 'waar', 'waarom', 'hoe', 'allemaal', 'ieder', 'beide', 'elk', 'weinig', 'meer', 'meest', 'anders', 'sommige', 'zodanig', 'Nee', 'noch', 'niet', 'alleen', 'eigen', 'dezelfde', 'zo', 'dan', 'te', 'heel', 's', 't', 'kan', 'zullen', 'net', 'don', 'moeten', 'nu']
    return(dict(zip(eng_sw, dut_sw)))

def DutchToEngStopWords():
    eng_sw = ['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', 'too', 'very', 's', 't', 'can', 'will', 'just', 'don', "don't", 'should', "should've", 'now', 'd', 'll', 'm', 'o', 're', 've', 'y', 'ain', 'aren', "aren't", 'couldn', "couldn't", 'didn', "didn't", 'doesn', "doesn't", 'hadn', "hadn't", 'hasn', "hasn't", 'haven', "haven't", 'isn', "isn't", 'ma', 'mightn', "mightn't", 'mustn', "mustn't", 'needn', "needn't", 'shan', "shan't", 'shouldn', "shouldn't", 'wasn', "wasn't", 'weren', "weren't", 'won', "won't", 'wouldn', "wouldn't"]
    dut_sw=['ik', 'me', 'mijn', 'mezelf', 'wij', 'onze', 'Onze', 'onszelf', 'u', 'uw', 'uw', 'jezelf', 'uzelf', 'hij', 'hem', 'zijn', 'zichzelf', 'ze', 'haar', 'zijn', 'zichzelf', 'het', 'haar', 'zelf', 'ze', 'hen', 'hun', 'hun', 'zich', 'wat', 'welke', 'wie', 'wie', 'deze', 'dat', 'deze', 'die', 'am', 'is', 'zijn', 'was', 'waren', 'worden', 'geweest', 'wezen', 'hebben', 'heeft', 'had', 'met', 'Doen', 'doet', 'deed', 'doen', 'een', 'een', 'de', 'en', 'maar', 'als', 'of', 'omdat', 'als', 'tot', 'terwijl', 'van', 'Bij', 'door', 'voor', 'met', 'over', 'tegen', 'tussen', 'in', 'door', 'gedurende', 'voordat', 'na', 'bovenstaande', 'beneden', 'naar', 'van', 'omhoog', 'beneden', 'in', 'uit', 'Aan', 'uit', 'over-', 'onder', 'opnieuw', 'verder', 'vervolgens', 'eenmaal', 'hier', 'Daar', 'wanneer', 'waar', 'waarom', 'hoe', 'allemaal', 'ieder', 'beide', 'elk', 'weinig', 'meer', 'meest', 'anders', 'sommige', 'zodanig', 'Nee', 'noch', 'niet', 'alleen', 'eigen', 'dezelfde', 'zo', 'dan', 'te', 'heel', 's', 't', 'kan', 'zullen', 'net', 'don', 'moeten', 'nu']
    return(dict(zip( dut_sw,eng_sw)))


